### ISSUE TITLE
Support specific version to install

### ISSUE THREAD

**Issue by lecoueyl** [pnpm/get.pnpm.io#18]
With the old installer https://github.com/pnpm/self-installer , the PNPM version could be specified with the environment variable `PNPM_VERSION` like this:

```
curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | PNPM_VERSION=1.16.2 node
```

The new installer does not seem to have this feature.
For example, when using PNPM on production, it is safer to have a specific version and avoid version drift between instances.

**Comment by zkochan** [comment]
Sounds good to me. I hope someone will help to implement it. I am not too good with bash scripting.

**Comment by lecoueyl** [comment]
I will submit a PR to implement this feature 👍
