### ISSUE TITLE
Updates to pnpm js install

### ISSUE THREAD

**Issue by Irevall** [pnpm/get.pnpm.io#21]
The latest pnpm version here is 6.16.
Can it get updated a bit more often or should I switch to `install.sh`?

**Comment by zkochan** [comment]
Why should it be updated? It is used to dynamically load the latest pnpm version.

**Comment by Irevall** [comment]
I mean the method mentioned [here](https://pnpm.io/installation#nodejs-is-preinstalled):
`curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm`
Doesn't it download v6.16 instead of the latest?

**Comment by zkochan** [comment]
It downloads v6.16 and installs the latest pnpm. So pnpm v6.16 is just used to install the latest pnpm.

**Comment by Irevall** [comment]
Oh okay, I thought it just install 6.16.
Thanks a lot for clarifying. 👍
