### ISSUE TITLE
install.sh can't install pnpm on Linux distros that use musl as libc.

### ISSUE THREAD

**Issue by hronro** [pnpm/get.pnpm.io#26]
Such as Alpine Linux.

**Comment by mekb-turtle** [comment]
The binary isn't linked with musl, you'll need to compile/link it yourself instead of using prebuilt releases. It's giving no such file or directory, not for the binary itself, but for glibc.

**Comment by kotx** [comment]
This issue depends on https://github.com/pnpm/pnpm/issues/3820

**Comment by zkochan** [comment]
I guess we can run `getconf GNU_LIBC_VERSION 2>&1 || true; ldd --version 2>&1 || true` and check if musl is used. If so, we can download the linuxstatic-x64 artifact.

**Comment by tucksaun** [comment]
fixed in #28?
