### ISSUE TITLE
`pnpm setup` instruction will result in duplicates in `$PATH` after sourcing startup files

### ISSUE THREAD

**Issue by xu-minghao317** [pnpm/get.pnpm.io#27]
After running `pnpm setup`, the followings are print

```shell
Appended new lines to $HOME/.zshrc

Next configuration changes were made:
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
```

However, this will make `source $HOME/.zshrc` generate duplicates in `$PATH`
~~How about checking the command existence before adding to `$PATH`?~~
How about checking if it is in the `$PATH` before adding it?

```shell
export PNPM_HOME="$HOME/Library/pnpm"
[[ ":$PATH:" == *":$PNPM_HOME:"* ]] || export PATH="$PNPM_HOME:$PATH"
```

**Comment by zkochan** [comment]
But we actually check if `.zshrc` has PNPM_HOME already and don't update it in that case.

**Comment by xu-minghao317** [comment]
Could you refer to where that checker is? I still get duplicates if I follow 🤔

```shell
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
```

I saw `pyenv` is doing this and it works well

```shell
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
```

Considering people using `corepack` where `pnpm` can be found in node directory, `[[ ":$PATH:" == *":$PNPM_HOME:"* ]]` replace `command -v pyenv >/dev/null`

**Comment by zkochan** [comment]
This is what `pnpm setup` adds to your shell config file:

```sh
# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
```

Then next time if you run setup again, it checks if there is a pnpm section in the config file and it is up-to-date.

**Comment by xu-minghao317** [comment]
I appreciate your explanation of how `pnpm setup` works, but I believe there may have been a misunderstanding of my issue.

I understand that `pnpm setup` checks whether the `pnpm` section already exists in the shell config file before updating it, and that it will not add duplicate lines in the file. However, my concern is that running `source .zshrc` or `exec zsh` will add duplicate paths to the`$PATH`.

The reason for this is that the `export PATH="$PNPM_HOME:$PATH"` script always adds the `$PNPM_HOME` directory to the beginning of the `$PATH` variable, without checking whether it already exists.

To avoid this, I suggested modifying the `export PATH="$PNPM_HOME:$PATH` script to check whether the `$PNPM_HOME` directory is already in the `$PATH` variable before adding it. This is similar to what the `pyenv` and many tools does.

I hope this clarifies my concern. Thank you again for your attention to this matter.

**Comment by zkochan** [comment]
I see, sounds good.

**Comment by xu-minghao317** [comment]
Thank you.

**Comment by levrik** [comment]
This change seems to have broken upgrading installations.

```
curl -fsSL https://get.pnpm.io/install.sh | sh -           
==> Downloading pnpm binaries 7.29.0
Copying pnpm CLI from /private/var/folders/y5/_yxr_tgx3xggc344718g4fp00000gn/T/tmp.ae1In5jq/pnpm to /Users/levrik/Library/pnpm/pnpm
 ERR_PNPM_BAD_SHELL_SECTION  The config file at "/Users/levrik/.zshrc already contains a pnpm section but with other configuration

If you want to override the existing configuration section, use the --force option
Install Error!
```

Sadly I couldn't figure out how to pass the `--force` option.

**Comment by xu-minghao317** [comment]
I think you can pass the flag as 
```bash
curl -fsSL https://get.pnpm.io/install.sh | sh -s -- --force
```

**Comment by zkochan** [comment]
I guess we could force always?

You can run this for now to override the config:

```
curl -fsSL https://get.pnpm.io/install.sh | NPM_CONFIG_FORCE=true sh -
```

**Comment by zkochan** [comment]
This will fix it: https://github.com/pnpm/get.pnpm.io/pull/33
